# Generated by Django 3.2.7 on 2021-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
